version: '3.8'

services:

  get_data:
    build:
      context: .
      dockerfile: src/get_data/Dockerfile
    depends_on:
      - postgres

    command: >
      sh -c "python src/database/health_check/check_db_health.py && python src/get_data/main.py"

  print_data:
    build:
      context: .
      dockerfile: src/print_data/Dockerfile
    depends_on:
      - postgres

    command: >
      sh -c "python src/database/health_check/check_db_health.py && python src/print_data/main.py"

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: